name: japx
description: Lightweight parser for the JSON:API (http://jsonapi.org/) structure.
version: 2.2.0
repository: https://github.com/infinum/flutter-plugins-japx
homepage: https://github.com/infinum/flutter-plugins-japx

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
